update FAQ visibility
glpi-project/doc pull request #110
Opened 2023-01-18 15:03 UTC by Rom1-B

Updated documentation for GLPI 10.1

PR : https://github.com/glpi-project/glpi/pull/13455

2023-01-25 15:53 UTC, cedric-anne approved these changes

2023-01-26 07:23 UTC, cedric-anne requested changes
Maybe documentation should explain that there is a change between GLPI 10.0 and 10.1 (using the `.. versionchanged` tag for instance).

2023-01-26 10:18 UTC, trasher approved these changes

2023-01-26 13:41 UTC, orthagh approved these changes

2023-02-08 17:29 UTC, cedric-anne approved these changes

2023-03-06 11:52 UTC, cconard96 requested changes

2023-03-06 11:52 UTC, cconard96 commented on source/modules/tools/knowledgebase.rst
> +Each article of the knowledge base must have one or several targets, a target being either an entity, a group, a profile or a user, to be readable. As long as an article has no target, it is visible
```suggestion
Each article of the knowledge base must have one or more targets, being entities, groups, profiles or users, to be readable. As long as an article has no target, it is visible only by its writer, is flagged as `unpublished` and appears in table `Unpublished articles` on the home page of the knowledge base.
```

2023-03-06 11:52 UTC, cconard96 commented on source/modules/tools/knowledgebase.rst
> +   You can publish an article to everyone, targeting the root entity.
```suggestion
   You can publish an article for everyone by targeting the root entity.
```

2023-03-06 13:35 UTC, cconard96 approved these changes

2023-03-06 13:48 UTC, merged