Trad/management
glpi-project/doc pull request #46
Opened 2021-01-29 15:32 UTC by fdechelle

translated management module:

- renamed gestion/ to management/
- translated all files

2021-01-29 23:19 UTC, cconard96 requested changes

2021-01-29 23:19 UTC, cconard96 commented on source/modules/management/contract.rst
> +   Notifications are configured at entity level, in menu **Configuration > Notifications** to define models and destination and in menu **Configuration > Entity** to enable notification, define defau
```suggestion
   Notifications are configured at entity level, in menu **Setup > Notifications** to define models and destination and in menu **Administration > Entities** to enable notification, define default values and a possible anticipation of notification.
```

2021-01-29 23:19 UTC, cconard96 commented on source/modules/management/documents.rst
> +   * Document types authorized in GLPI according to their extension are defined in **Configuration** > **Drop-downs** > **Management** > **Document types**
```suggestion
   * Document types authorized in GLPI according to their extension are defined in **Setup** > **Dropdowns** > **Management** > **Document types**
```

2021-01-29 23:19 UTC, cconard96 commented on source/modules/management/licenses.rst
> +   License management is not automated, a human following is needed for informations update.
```suggestion
   License management is not automated, a human follow-up is needed for information update.
```
Or
License management is not automated, a manual follow-up is needed for information update.

2021-02-01 07:02 UTC, trasher approved these changes
OK for me, see Curtis comments :)

2021-02-01 09:28 UTC, cconard96 approved these changes

2021-02-01 09:39 UTC, merged